import type { Metadata } from "next";
import "./globals.css";
import { satoshi } from "@/lib/fonts";
import Providers from "@/lib/utils/providers";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
import { ReactNode } from "react";
import KofiSupport from "@/components/Common/Kofi";
import dynamic from "next/dynamic";

export const metadata: Metadata = {
  title: "Ceelyrics - Next",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
  modal: ReactNode;
}

// const KofiButton = dynamic(() => import("@/components/Common/Kofi/index"));

const RootLayout: React.FC<RootLayoutProps> = (props) => {
  return (
    <html lang="en">
      <body className={`${satoshi.className} dark:bg-background-950 dark:text-text-50`}>
        <Providers>
          <Navbar />
          {props.modal}
          {props.children}
          <Footer />
        </Providers>

        {/* <KofiButton /> */}
      </body>
    </html>
  );
};

export default RootLayout;
