import type { Metadata } from "next";
import "./globals.css";
import { dmSans } from "@/lib/fonts";
import Providers from "@/lib/utils/providers";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";

export const metadata: Metadata = {
  title: "Ceelyrics - Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} dark:bg-background-950 dark:text-text-50`}>
        <Providers>
          <Navbar />
          {/* <div className="h-[6rem]"></div> */}
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
