import type { Metadata } from "next";
import "./globals.css";
import { dmSans } from "@/lib/fonts";
import Providers from "@/lib/utils/providers";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Ceelyrics - Next",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
  modal: ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = (props) => {
  return (
    <html lang="en">
      <body className={`${dmSans.className} dark:bg-background-950 dark:text-text-50`}>
        <Providers>
          <Navbar />
          {props.modal}
          {props.children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
